action_space: 1
agent_type: random
alpha: 1e-3
batch_size: 64
buffer_size: 300
data_path: plot_data/random_agent/random_agent
discount: 0.99
env: gyms:gyms/CustomMountainCar-v0
epsilon: 0.1
eval_last_agent: false
eval_mode: false
eval_path: ./models/model.pth
k: 64
log_dir: ./logs/train
max_steps: 200
n_bins: (72,28)
num_episodes: 100
observation_space: 2
plot_data: plot_data/default
reward_factor: 2
rnd_alpha: 0.01
use_target_network: false
